 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for Port Module.
 *
 * Author: Kareem Hassaan
 ******************************************************************************/
 
#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version "
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version "
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_PinsConfiguration =
                                   {
									PortConf_Pin01,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin02,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin03,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin04,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin05,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin06,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin07,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin08,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									
									PortConf_Pin09,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin10,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin11,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin12,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin13,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin14,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin15,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin16,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									
									PortConf_Pin17,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin18,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin19,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin20,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin21,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin22,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_OUT,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin23,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin24,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									
									PortConf_Pin25,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin26,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin27,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin28,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin29,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin30,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin31,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
									PortConf_Pin32,PORT_PIN_MODE_DIO,PORT_PIN_MODE_DIO,PORT_PIN_IN,PORT_PIN_LEVEL_LOW,TRUE,TRUE,FALSE,
								   };
